feat: allows specifying subdir when creating adr

diff --git a/src/adr-new b/src/adr-new
--- a/src/adr-new
+++ b/src/adr-new
@@ -1,133 +1,78 @@
 #!/bin/bash
 set -e
 eval "$($(dirname $0)/adr-config)"
+echo "adr_bin_dir: $adr_bin_dir"
+echo "adr_template_dir: $adr_template_dir"
 
-## usage: adr new [-s SUPERCEDED] [-l TARGET:LINK:REVERSE-LINK] TITLE_TEXT...
+## usage: adr new [SUBDIR] TITLE...
 ##
-## Creates a new, numbered ADR.  The TITLE_TEXT arguments are concatenated to
+## Creates a new, numbered ADR.  The TITLE arguments are concatenated to
 ## form the title of the new ADR.  The ADR is opened for editing in the
 ## editor specified by the VISUAL or EDITOR environment variable (VISUAL is
-## preferred; EDITOR is used if VISUAL is not set).  After editing, the
-## file name of the ADR is output to stdout, so the command can be used in
-## scripts.
-##
-## If the ADR directory contains a file `templates/template.md`, this is used as
-## the template for the new ADR.  Otherwise a default template is used that
-## follows the style described by Michael Nygard in this article:
-##
-##   http://thinkrelevance.com/blog/2011/11/15/documenting-architecture-decisions
-##
-## Options:
-##
-## -s SUPERCEDED   A reference (number or partial filename) of a previous
-##                 decision that the new decision supercedes. A Markdown link
-##                 to the superceded ADR is inserted into the Status section.
-##                 The status of the superceded ADR is changed to record that
-##                 it has been superceded by the new ADR.
-##
-## -l TARGET:LINK:REVERSE-LINK
-##                 Links the new ADR to a previous ADR.  
-##                 TARGET is a reference (number or partial filename) of a 
-##                 previous decision. 
-##                 LINK is the description of the link created in the new ADR.
-##                 REVERSE-LINK is the description of the link created in the
-##                 existing ADR that will refer to the new ADR.
-##
-## Multiple -s and -l options can be given, so that the new ADR can supercede 
-## or link to multiple existing ADRs.
-##
-## E.g. to create a new ADR with the title "Use MySQL Database":
-##
-##     adr new Use MySQL Database
-##
-## E.g. to create a new ADR that supercedes ADR 12:
-##
-##     adr new -s 12 Use PostgreSQL Database
-##
-## E.g. to create a new ADR that supercedes ADRs 3 and 4, and amends ADR 5:
-##
-##     adr new -s 3 -s 4 -l "5:Amends:Amended by" Use Riak CRDTs to cope with scale
-##
+## preferred; EDITOR is used if VISUAL is not set).
 
-superceded=()
-links=()
-
-while getopts s:l: arg
-do
-    case "$arg" in
-        s)
-            superceded+=("$OPTARG")
-            ;;
-		l)
-			links+=("$OPTARG")
-			;;
-        --)
-            break
-            ;;
-        *)
-            echo "Not implemented: $arg" >&2
-            exit 1
-            ;;
-    esac
-done
-shift $((OPTIND-1))
-
-dstdir=$("$adr_bin_dir/_adr_dir")
-template="$ADR_TEMPLATE"
-if [ -z $template ]
-then
-    template="$dstdir/templates/template.md"
-    if [ ! -f "$template" ]
-    then
-        template="$adr_template_dir/template.md"
-    fi
-fi
-
-title="$@"
-
-if [ -z "$title" ]
-then
-    echo ERROR: no title given
+base_adr_dir=$("$adr_bin_dir/_adr_dir")
+echo "base_adr_dir: $base_adr_dir"
+if [ $# -eq 0 ]; then
+    echo "Error: Missing title" >&2
     exit 1
 fi
 
-if [ -d $dstdir ]
-then
-    maxid=$(ls $dstdir | grep -Eo '^[0-9]+' | sed -e 's/^0*//' | sort -rn | head -1)
-    newnum=$(($maxid + 1))
+# Parse arguments
+subdir=""
+while [[ $# -gt 0 ]]; do
+    case $1 in
+        --subdir)
+            subdir="$2"
+            shift 2
+            ;;
+        *)
+            break
+            ;;
+    esac
+done
+
+# Get the title from remaining arguments
+title="$*"
+
+slug=$(echo -n "$title" | tr -Ccs '[:alnum:]' - | tr '[:upper:]' '[:lower:]' | sed -e 's/^-*//' -e 's/-*$//')
+
+dstdir="$base_adr_dir/$subdir"
+mkdir -p "$dstdir"
+echo "dstdir: $dstdir"
+# Find the highest existing ADR number
+maxid=$(ls "$dstdir" | grep -Eo '^[0-9]+' | sort -rn | head -1)
+
+# Calculate the new ADR number
+newnum=$((${maxid:-0} + 1))
+
+# Format the new ADR ID with leading zeros
+newid=$(printf "%04d" $newnum)
+
+# Explanation:
+# 1. We list the contents of the destination directory and extract the numeric prefixes
+# 2. We sort these numbers in reverse order and take the first (highest) one
+# 3. If no numbers are found, maxid will be empty, so we use 0 as the default
+# 4. We increment the highest number (or 0) by 1 to get the new ADR number
+# 5. We format the new number as a 4-digit zero-padded string (e.g., 0001, 0002, etc.)
+
+# Construct the file path
+base_dir="$base_adr_dir"
+if [[ -n "$subdir" ]]; then
+    file_path="$base_dir/$subdir/$newid-$slug.md"
+    mkdir -p "$(dirname "$file_path")"
 else
-    newnum=1
+    file_path="$base_dir/$newid-$slug.md"
 fi
 
-newid=$(printf "%04d" $newnum)
-slug=$(echo -n $title | tr -Ccs [:alnum:] - | tr [:upper:] [:lower:] | sed -e 's/[^[:alnum:]]*$//' -e 's/^[^[:alnum:]]*//')
-dstfile=$dstdir/$newid-$slug.md
+# Create the file content
 date=${ADR_DATE:-$(date +%Y-%m-%d)}
 
-mkdir -p $dstdir
-cat $template | sed \
+cat "$adr_template_dir/template.md" | sed \
     -e "s|NUMBER|$newnum|" \
     -e "s|TITLE|$title|" \
     -e "s|DATE|$date|" \
     -e "s|STATUS|Accepted|" \
-    > $dstfile
+    > "$file_path"
 
-for target in "${superceded[@]}"
-do
-	"$adr_bin_dir/_adr_add_link" "$target" "Superceded by" "$dstfile"
-	"$adr_bin_dir/_adr_remove_status" "Accepted" "$target"
-	"$adr_bin_dir/_adr_add_link" "$dstfile" "Supercedes" "$target"
-done
-
-for l in "${links[@]}"
-do
-	target="$(echo $l | cut -d : -f 1)"
-	forward_link="$(echo $l | cut -d : -f 2)"
-	reverse_link="$(echo $l | cut -d : -f 3)"
-	
-	"$adr_bin_dir/_adr_add_link" "$dstfile" "$forward_link" "$target"
-	"$adr_bin_dir/_adr_add_link" "$target" "$reverse_link" "$dstfile"
-done
-
-${VISUAL:-${EDITOR:-true}} $dstfile
-echo $dstfile
+echo "ADR file created: $file_path"
